import { EdgeStruct } from "./Edge";

const strokeWidth = 2;

export const MockEdgeStructData: EdgeStruct[] = [
  {
    type: "bezier",
    source: "1",
    target: "2",
    id: "edge 1",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "2",
    target: "3",
    id: "edge 2",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "2",
    target: "4",
    id: "edge 3",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "2",
    target: "6",
    id: "edge 4",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "2",
    target: "7",
    id: "edge 5",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "1",
    target: "8",
    id: "edge 6",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "8",
    target: "9",
    id: "edge 7",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "8",
    target: "10",
    id: "edge 8",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "8",
    target: "11",
    id: "edge 9",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "8",
    target: "12",
    id: "edge 10",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "1",
    target: "13",
    id: "edge 11",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "1",
    target: "14",
    id: "edge 12",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "13",
    target: "15",
    id: "edge 13",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "13",
    target: "16",
    id: "edge 14",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "13",
    target: "17",
    id: "edge 15",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "13",
    target: "18",
    id: "edge 16",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "14",
    target: "19",
    id: "edge 17",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "14",
    target: "20",
    id: "edge 18",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "14",
    target: "21",
    id: "edge 19",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
  {
    type: "bezier",
    source: "14",
    target: "22",
    id: "edge 20",
    animated: true,
    style: { strokeWidth: strokeWidth },
  },
];
